{% set name = "liquidpy" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/liquidpy-{{ version }}.tar.gz
  sha256: 9f5fefccb5f48dd31a49d78d289786527946e51508392d9353299c8be35c2d06
  patches:
    # remove optional dependency (pip doesn't understand 'optional')
    - no-frontmatter.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - python >=3.6
    - jinja2 >=3.0.0,<4.0.0

test:
  requires:
    - pip
  imports:
    - liquid
  commands:
    - python -m pip check

about:
  home: https://github.com/pwwang/liquidpy
  doc_url: https://pwwang.github.io/liquidpy/
  dev_url: https://github.com/pwwang/liquidpy.git
  summary: A port of liquid template engine for python
  license: Apache-2.0
  license_file: LICENSE
  description: A port of liquid template engine for python. This is compatible with standard Liquid template engine. Variations, such as Shopify and Jekyll are not fully supported yet.

extra:
  recipe-maintainers:
    - duncanmmacleod
