{% set name = "liquidpy" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/liquidpy-{{ version }}.tar.gz
  sha256: bd025ca208342e4639c709efdcfc35ba92b17c3d41d8d78ee08ca69b3833245c
  patches:
    # use poetry-core
    - poetry-core.patch
    # remove optional dependencies (pip doesn't understand 'optional')
    - no-optional-dependencies.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip <21.3
    - poetry-core
    - python >=3.6
  run:
    - python >=3.6
    - jinja2 >=3.0.0,<4.0.0

test:
  requires:
    - pip
  imports:
    - liquid
  commands:
    - python -m pip check

about:
  home: https://github.com/pwwang/liquidpy
  doc_url: https://pwwang.github.io/liquidpy/
  dev_url: https://github.com/pwwang/liquidpy.git
  summary: A port of liquid template engine for python
  license: Apache-2.0
  license_file: LICENSE
  description: A port of liquid template engine for python. This is compatible with standard Liquid template engine. Variations, such as Shopify and Jekyll are not fully supported yet.

extra:
  recipe-maintainers:
    - duncanmmacleod
